version: "3.3"
services:
  db_demo:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "5555:3306"
    volumes:
      - "./db/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456Aa@
      - MYSQL_DATABASE=tacn
      - MYSQL_USER=tacn
      - MYSQL_PASSWORD=123456Aa@
    networks:
      - mynet

  server_demo:
    image: node:14-alpine
    depends_on:
      - db_demo
    ports:
      - 3333:3000
    command: "sh -c 'yarn && yarn start'"
    networks:
      - mynet
    volumes:
      - ./server:/app
    working_dir: /app
    environment:
      - WAIT_HOSTS=db_demo:5555
    links:
      - db_demo
    restart: always

  web:
    image: node:14-alpine
    ports:
      - 4444:3000
    volumes:
      - ./web:/app
    working_dir: /app
    command: "sh -c 'yarn && yarn start'"

networks:
  mynet:
    driver: bridge
